[build]
  command = "npm run build"
  publish = "dist/appointment/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"

[[plugins]]
  package = "@netlify/angular-runtime"
  [plugins.inputs]
    enabled = false
    angularConfigPath = "angular.json"